service: appointment-cl

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: production
  region: us-east-2
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 15
  httpApi:
    cors: true
  environment:
    NODE_OPTIONS: --enable-source-maps

functions:
  api:
    handler: dist/lambda.handler
    timeout: 29
    events:
      - httpApi:
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: '/{proxy+}'
      - sqs:
          arn: arn:aws:sqs:us-east-2:222964727514:sqs_cl
          batchSize: 1

plugins:
  - serverless-offline
  - serverless-jetpack